### ISSUE TITLE
Experiments won't run when no soundcard is present

### ISSUE THREAD

**Issue by dschreij** [open-cogsci/OpenSesame#239]
When the soundcard is engaged by another program, or there is no soundcard present, an experiment immediately crashes upon start with the message

```
"Error: No available audio device"
```

originiting from (pygame.)mixer.init()

Shouldn't OS also  be able to run on machines without a sound card? Maybe an extra check in the back-end settings, with which you can specify if to look for a soundcard would help with this problem.

**Comment by crsh** [comment]
Hi, I just installed OpenSesame 3.0.0 on Ubunutu 14.04 and tried to run an example experiment. But I get this error message:

> item-stack: ``
> exception message: No available audio device
> time: Tue Oct 20 15:16:26 2015
> exception type: error

Traceback:

>   File "/usr/lib/pymodules/python2.7/libqtopensesame/misc/process.py", line 140, in run
    exp.run()
  File "/usr/lib/pymodules/python2.7/libopensesame/experiment.py", line 379, in run
    self.init_display()
  File "/usr/lib/pymodules/python2.7/libopensesame/experiment.py", line 722, in init_display
    canvas.init_display(self)
  File "/usr/lib/pymodules/python2.7/openexp/canvas.py", line 66, in init_display
    cls.init_display(experiment)
  File "/usr/lib/pymodules/python2.7/openexp/_canvas/psycho.py", line 375, in init_display
    pygame.mixer.init()
error: No available audio device

Here's my sound device:

    ~$ lspci | grep -i audio
    00:1b.0 Audio device: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller (rev 04)

Any idea what's going on?

P.S.: Sorry if this isn't the right place to discuss this issue. It poped up when I was googeling the problem.

**Comment by crsh** [comment]
I just ran some more updates and it seems to work. Sorry for the false alarm.
