### ISSUE TITLE
English language option in preference menu missing

### ISSUE THREAD

**Issue by PascalKieslich** [open-cogsci/OpenSesame#558]
I really like that OpenSesame now (for some time) offers the option to select the menu language via the preference menu. However, as a user with a German system environment I have one problem: The language options do not include English (or en_En) - and the "[Default]" option leads to a German menu for me. The current workaround for me is to select translatables - but it might be helpful to offer en en_EN option in future OpenSesame versions.

Best,

Pascal

**Comment by PascalKieslich** [comment]
Forgot to mention: I am using OpenSesame 3.1.9 on Windows.

**Comment by smathot** [comment]
Hi Pascal,

Thanks—this is indeed not very user friendly.

Cheers!
Sebastiaan
