### ISSUE TITLE
[Windows] Suggestion: detect DPI / zoom setting and warn user if it will cause a problem

### ISSUE THREAD

**Issue by alisdt** [open-cogsci/OpenSesame#567]
On Windows 10 I've noticed that anything other that 100% "zoom" (the DPI setting in Display Settings) causes canvases to be rendered incorrectly when the native monitor resolution is selected. OpenSesame could detect this and warn the user to change this setting.

(Alternatively, as the Windows docs say, OpenSesame could be made "DPI aware", but that would be a lot of work for just one platform ....)

Example code here which could no doubt be accessed via ctypes / cffi:

https://stackoverflow.com/questions/5977445/how-to-get-windows-display-settings

**Comment by smathot** [comment]
Hi,

Thanks for this! Could you describe the issue in a bit more detail?

- Are canvas objects rendered incorrectly during the experiment, or when previewing the sketchpad in the GUI?
- And in what sense are they rendered incorrectly? What do you see?
- Does this happen with all backends? If not, with which ones?
- Does this happen both fullscreen and window mode?

Cheers!
Sebastiaan

**Comment by alisdt** [comment]
Hi,

I was talking about canvases in inline code -- not sure about sketchpads. Here's some more detail as steps to reproduce:

1. On a Windows 10 PC with a HD monitor (1920x1080), ensure that the "Zoom" is set to the default of 150% (right-click on Desktop, select "Display settings")
2. Start OpenSesame 3.1.9
3. In the experiment General Properties, set the resolution to 1920x1080
4. Create a single inline code item with the following code in the Run tab:
```python
c = canvas()

# draw 9 dots
for x in [-960,0,960]:
	for y in [-540,0,540]:
		c.circle(x,y,100)

c.show()

_, _ = keyboard().get_key()
```
5. Run the experiment and observe a single circle in the middle of the screen. The expected result is quarter circles at the corners, half circles at the edges and a full circle in the middle.
6. Going back into Windows' "Display properties", change the Zoom setting to 100%
7. Run the experiment again and observe that the expected result appears.

Tested with expyriment, psychopy and legacy, with the same result in each case. I haven't tested windowed mode yet.

**Comment by alisdt** [comment]
The sketchpad equivalent of the above exhibits the same behaviour. To reproduce, follow the steps above but with a sketchpad item instead of an inline code item, with the script:

```
set start_response_interval no
set reset_variables no
set duration keypress
set description "Displays stimuli"
draw circle color=white fill=0 penwidth=1 r=100 show_if=always x=-960 y=-540 z_index=0
draw circle color=white fill=0 penwidth=1 r=100 show_if=always x=-960 y=0 z_index=0
draw circle color=white fill=0 penwidth=1 r=100 show_if=always x=-960 y=540 z_index=0
draw circle color=white fill=0 penwidth=1 r=100 show_if=always x=0 y=-540 z_index=0
draw circle color=white fill=0 penwidth=1 r=100 show_if=always x=0 y=0 z_index=0
draw circle color=white fill=0 penwidth=1 r=100 show_if=always x=0 y=540 z_index=0
draw circle color=white fill=0 penwidth=1 r=100 show_if=always x=960 y=-540 z_index=0
draw circle color=white fill=0 penwidth=1 r=100 show_if=always x=960 y=0 z_index=0
draw circle color=white fill=0 penwidth=1 r=100 show_if=always x=960 y=540 z_index=0
```

**Comment by alisdt** [comment]
A windowed experiment does not have this problem, so long as the window still fits on the screen -- the window is simply scaled. E.g. on a 1080px high display, I would expect a 500px window to take up roughly half of the vertical space. When zoom is set to 150%, it takes up roughly 2/3 of the vertical space, but the contents look correct.

**Comment by smathot** [comment]
Thanks for this. I'm going to find a Windows 10 system and see if I can reproduce it. (Windows 7 doesn't seem to exhibit this behavior.)

**Comment by smathot** [comment]
Thanks, I see what you mean now. Rendering is not incorrect as such, but just scaled, as Windows does with all program that aren't DPI aware. Still, it can be confusing, so it would be worthwhile to notify the user of this in one way or another. Maybe a message at the start of the experiment if the zoom settings are anything other than 100%.

**Comment by smathot** [comment]
As of 3.2.0a12, there's a notification when display scaling is anything other than 100%. The webbrowser is also scaled now, so the UI should generally be a bit more HD friendly.
