### ISSUE TITLE
Ctrl+f twice to make search box disappear

### ISSUE THREAD

**Issue by roelofvsr** [open-cogsci/OpenSesame#569]
Current the search window in an inline script only appears on pressing ctrl+f, but it does not disappear after second press of ctrl+f, would really appreciate such a feature

**Comment by smathot** [comment]
Hi Roelof,

Thanks for your input. Right now the behavior that `ctrl+f` opens the search bar, and `escape` closes it. I checked in two other editors (Atom and Gedit) and they behave the same way. Do you have examples of editors that do this differently, and that behave better in your opinion?

Cheers!
Sebastiaan

**Comment by roelofvsr** [comment]
Hi Sebastiaan,
Sorry for the late reply git still sends messages to my old university address that I do not check regularly.
Regarding the ctrl+f you are right esc seems a logical default; bit of a blind spot on my end, it just felt intuitive to call and exit the search through the same combination since it would reduce the need for multiple different types of key presses, bit similar to using alt+tab for screen switching, but this is perhaps just me I don't have data that backs this up as something that users would actually find handy. Thanks for all the feedback, still very impressed with opensesame, perhaps until some conference :-)

Regards,
Roelof Roessingh

THIS EMAIL ADDRESS WILL DISAPPEAR; contact me on:
roelofroessingh@protonmail.com

-------------------------------------------------
Research-Assistant
Vrije Universiteit Amsterdam
Experimental and Applied Psychology
Van de Boechorststraat 1, 1081 BT, Amsterdam
room: 1 B - 75
________________________________
Van: Sebastiaan Mathot [notifications@github.com]
Verzonden: woensdag 15 november 2017 4:23
Aan: smathot/OpenSesame
CC: Roessingh, R.V.S.; Author
Onderwerp: Re: [smathot/OpenSesame] Ctrl+f twice to make search box disappear (#569)


Hi Roelof,

Thanks for your input. Right now the behavior that ctrl+f opens the search bar, and escape closes it. I checked in two other editors (Atom and Gedit) and they behave the same way. Do you have examples of editors that do this differently, and that behave better in your opinion?

Cheers!
Sebastiaan

**Comment by smathot** [comment]
Hi Roelof,

I'll close this then. I do see what you mean, but I think the current behavior (`Ctrl+F` to open, `Esc` to close) is how most editors work, and hence what most users will find intuitive.

Thanks again for your input!

Sebastiaan
