### ISSUE TITLE
Pseudo randomization does not work when reading from file

### ISSUE THREAD

**Issue by roelofvsr** [open-cogsci/OpenSesame#570]
Pseudo randomization options do not work work when reading variables from file, might be an easy fix, 
Currently an easy work around with defining a dummy variable, seems to work:
http://forum.cogsci.nl/index.php?p=/discussion/comment/11696/#Comment_11696

**Comment by smathot** [comment]
Thanks for this! (And for helping people out on the forum with this issue.) I just pushed a fix.
