### ISSUE TITLE
"Back-end settings" button links general script

### ISSUE THREAD

**Issue by eort** [open-cogsci/OpenSesame#575]
When clicking on the "Back-end settings button", Opensesame opens the general script editor. 
Tested on Ubuntu 16.04 and 17.04

**Comment by smathot** [comment]
Hi Eduard,

Thanks but this has already been fixed (see #554) in 3.2!

Cheers,
Sebastiaan

**Comment by eort** [comment]
Oh shit.
Sorry, I haven't seen that one. But good to hear it has been fixed. 

Eduard
