### ISSUE TITLE
File permissions on /Applications/OpenSesame.app/Contents/MacOS/OpenSesame incorrect

### ISSUE THREAD

**Issue by bochoven** [open-cogsci/OpenSesame#578]
The permissions on `/Applications/OpenSesame.app/Contents/MacOS/OpenSesame` are
```
-rwxr--r--
```

which is a problem when the application is installed by root (or someone else). OpenSesame fails to start for anyone that is not the owner. Could you please change the permissions to

```
-rwxr-xr-x
```

(OpenSesame 3.1.9)

**Comment by dschreij** [comment]
Hi Arjen,

That's a serious flaw. I'm amazed none noticed it earlier. I'll look into this. We're about to release a new version of OpenSesame (3.2) and I will fix this before release.

**Comment by dschreij** [comment]
This should be fixed in the next release (3.2). On my system the permissions have been set correctly at least, and hopefully that translates to your system too. Once OS 3.2 is out (in the next few days), could you test this for us and let us know?

**Comment by bochoven** [comment]
Sure! I created an autopkg recipe for OpenSesame that fixes the issue: https://github.com/autopkg/bochoven-recipes/tree/master/OpenSesame

If the next release is fixed, I'll remove the workaround.
