### ISSUE TITLE
OS 3.2.0 on Ubuntu 16.04 does not open a window with expyriment and psychopy

### ISSUE THREAD

**Issue by dschreij** [open-cogsci/OpenSesame#582]
When running an experiment on Ubuntu 16.04 using OpenSesame 3.2.0b1 Kafkaesque Koffka, the process hangs at the moment a window should be opened to show the experiment in. The legacy backend works fine.

My gut feeling is that this is an OpenGL issue (and thus not an OpenSesame one), but I'm going to report it here regardless, because I think it's a good idea to keep this on the radar. Other tests with OpenGL work fine (glxgears) so OpenGL itself might not be the problem. The support of (older) AMD cards for Ubuntu >= 16.04 is severely lacking at the moment, so I highly suspect this to be a driver issue (I'm using the open source AMD drivers that come with Ubuntu, as proprietary support for my video card stopped with 14.04). Newer cards or from a different brand hopefully work fine, but let's just keep an eye open for other people bumping into this problem too.

**Comment by mirh** [comment]
Putting aside bugs (which you'd usually get segfaults, reports, and whatnot in the terminal), the mesa 11.2 version that ships in Xenial should provide every supported radeon feature at least up to opengl 3.3. 
That should be enough for everything.

**Comment by smathot** [comment]
I'm closing this issue since it I think it's a system-specific issue that has likely been resolved with system updates.
