### ISSUE TITLE
Win10: OS 3.2.1-2 portable does not run from a dir with unicode characters

### ISSUE THREAD

**Issue by dschreij** [open-cogsci/OpenSesame#588]
OpenSesame portable 3.2.1-2 does not start up when being run from a folder with unicode characters. Instead, the following error message pops up:

![afbeelding](https://user-images.githubusercontent.com/689044/36630335-407253dc-1965-11e8-9f9b-f3dc5ead0237.png)

**Comment by smathot** [comment]
Excellent, thanks for spotting this!
