### ISSUE TITLE
Random Mouse clicks break Keyboard response in legacy backend

### ISSUE THREAD

**Issue by wolfgangwalther** [open-cogsci/OpenSesame#603]
Windows 7 / Python 2.7 / OpenSesame 3.2.1 (experienced that before as well)

This affecty only the **legacy** backend, expyriment and psycho work fine.

Whenever the experiment waits for a keyboard response, a couple of random mouse clicks break the keyboard response - ie no keyboard response will be registered after that anymore.

Testcase:
Basic Template, switch to legacy.
Start the experiment, click (AND move between the clicks!) the mouse a couple of times.
Keyboard is not working anymore.

This does not affect a timeout set on a keyboard response (finishes fine), but a keyboard response after that will be affected as well.

**Comment by smathot** [comment]
Thanks for this. The issue was that mouse-motion events clogged up the event cue. I had never noticed that. The current fix can also break in principle, for example when a large number of mouse clicks fill up the event cue. But that's unlikely to happen, so for now II think this is sufficient.
