### ISSUE TITLE
Different Canvas elements_at() behavior for psycho vs rest

### ISSUE THREAD

**Issue by mariansauter** [open-cogsci/OpenSesame#606]
I am using the ``my_canvas.elements_at(var.cursor_x, var.cursor_y)``

this leads to different return values depending on the back-end (which is not wanted I guess?):

Psycho returns
``['__background__', 'my_stimulus']``

Legacy/droid/expyriment return
``['my_stimulus']``

is there a way to detect the back-end from inside the code so I can patch a solution for my own code?

**Comment by smathot** [comment]
Thanks for reporting this! The `__background__` element is, as you might expect, a rectangle that is drawn to give the background a color. But it's counterintuitive that this is treated as a regular element, so it's better to hide it. I will push a fix in a second.

**Comment by mariansauter** [comment]
It is counter-intuitive but if possible, I would love to have a similar functionality with expyriment as well. I started developing an experiment with the psycho backend and then switched to expyriment where I immediately missed the functionality to manipulate an existing background without redrawing everything. 

Because as it is right now with psycho, you can actually draw and ``show()`` the canvas, then change the background color with 

``my_canvas[‘__background__’].color = ‘red’``

and show it again

``my_canvas.show()``and the background has changed. 

Changing the background with ``my_canvas.background_color()``only works when the background is redrawn (f.e. with ``clear()``).

Maybe it is better to not have it listed in ``elements_at()``but still make it accessible somehow as ``my_canvas[‘__background__’]`` ?
