### ISSUE TITLE
copy_sketchpad not working with xpyriment backend

### ISSUE THREAD

**Issue by wolfgangwalther** [open-cogsci/OpenSesame#608]
Windows 7 / 64 bit / Python 2.7 / OpenSesame 3.2.1

I created a new template experiment and inserted an inline script just after the welcome sketchpad, which reads in the `run` section:
```python
canvas = copy_sketchpad('welcome')
canvas.show()
clock.sleep(2000)
```

I expect the welcome sketchpad to show until I press any key and then an additional two seconds more. However as soon as I press a key, instead of the text `OpenSesame 3.2 <i>Kafkaesque Koffka</i>` there is just a white rectangular box on the black background.

This only affects the xpyriment backend, legacy and psycho work fine.

I did some more testing on different sketchpad elements:
`image` and `fixdot` are drawn fine on the copied sketchpad.
`textline`, `line`, `arrow`, `rect`, `circle`, `ellipse`, `gabor` and `noise` are just drawn as a white rectangular box instead.

**Comment by smathot** [comment]
Thanks again, Wolfgang.
