### ISSUE TITLE
3.2.1 disallows item name 'response' and fails to open older experiments

### ISSUE THREAD

**Issue by wolfgangwalther** [open-cogsci/OpenSesame#610]
Windows 7 / 64bit / Python 2.7 / OpenSesame 3.2.1

Trying to set an item name to `response` won't work anymore - the item name will be changed to `response_1` immediately, without another item with the same name. This was possible before.

Trying to open an older experiment that was created with 3.1.9 and that included such an item made OpenSesame rename the item itself to `response_1` - but not the references. This lead to the following error (dialog box):
`Extension undo_manager misbehaved on event open_experiment (see debug window for stack trace)`

And the debug window:
`No item named "response"`

In my case this was within a coroutine. However opening the coroutine in OpenSesame to try to change the name was not possible, because whenever I opened it, I just got the following error:
``` 
Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenSesame\lib\site-packages\libqtopensesame\widgets\tree_overview.py", line 329, in mousePressEvent
    u'script'           : target_item.to_string(),
  File "C:\Program Files (x86)\OpenSesame\share\opensesame_plugins\coroutines\oscoroutines\_coroutines.py", line 116, in to_string
    if self.is_oneshot_coroutine(item_name):
  File "C:\Program Files (x86)\OpenSesame\share\opensesame_plugins\coroutines\oscoroutines\_coroutines.py", line 85, in is_oneshot_coroutine
    return self.experiment.items[item_name].is_oneshot_coroutine
  File "C:\Program Files (x86)\OpenSesame\lib\site-packages\libopensesame\item_store.py", line 319, in __getitem__
    raise osexception(u'No item named "%s"' % name)
osexception: 
No item named "response"

item-stack: 
time: Thu Mar 08 22:08:17 2018
```

If disallowing `response` as an item name is by design, then I feel opening those files should rewrite the references as well. But what reason would there be to not allow `response` as a name anymore? `response` just feels natural for... exactly that: a response!

**Comment by smathot** [comment]
Hi Wolfgang,

Thanks again for reporting this. The disallowing of `response` as item name is intentional, because this could result to conflicting variable names. However, this should of course be handled gracefully when opening older experiments in which this is allowed.

Cheers!
Sebastiaan
