### ISSUE TITLE
Does SHOW IF (in the Feedback object) still work?

### ISSUE THREAD

**Issue by R180** [open-cogsci/OpenSesame#611]
In the newest version of OpenSesame which I downloaded today (3.2.1-py2.7-win32-2), the SHOW IF functionality--in the feedback object--does not appear to work. It's supposed to display WRONG and/or TOO SLOW only if the response is incorrect or too slow. A very simple demonstration experiment is attached.

[Is SHOW IF broken.zip](https://github.com/smathot/OpenSesame/files/1799562/Is.SHOW.IF.broken.zip)

**Comment by smathot** [comment]
Thanks for your feedback! This was indeed a bug, it has already been fixed in #592, and this fix will be included in 3.2.2.
