### ISSUE TITLE
File pool automatically cleared on Windows

### ISSUE THREAD

**Issue by smathot** [open-cogsci/OpenSesame#619]
There have been several reports on the forum of people who could no longer save their experiment because the file-pool folder did not exist. It seems that this happens when Windows automatically removes temporary files when OpenSesame has been running for a long time.

**Comment by dschreij** [comment]
I think the convention nowadays is to use the user's AppData folder for storing application data instead. If you ever want to get OpenSesame into the Windows Store (God knows why) or make it an UWP app (if MicroSoft ever starts to support Python with this), you may want to store everything related to OpenSesame there. This includes application settings that as far as I can remember are currently stored in an `.opensesame` folder in the user's home folder (but you might already no longer be doing this, I haven't checked in a while)

You should easily retrieve the path to this folder by using `os.getenv('APPDATA')`

Some guidelines/sources: 
- https://docs.microsoft.com/en-us/windows/uwp/design/app-settings/store-and-retrieve-app-data
- https://www.howtogeek.com/318177/what-is-the-appdata-folder-in-windows/
- https://stackoverflow.com/questions/13184414/how-can-i-get-the-path-to-the-appdata-directory-in-python

If I recall correctly, you are already using the AppData folder for other purposes, so the above may be old news for you, but still.

**Comment by smathot** [comment]
Thanks for this. The pool is actually already in the appdata folder, at least on my Windows system. However, it seems that Windows 10 now has an option to detect unused temp files and clear them up after a while. That seems to be what happens when you leave OpenSesame running for a long time without doing anything with the file pool. So I added an extension that touches the file pool every once in a while. Hopefully that resolves the issue.
