### ISSUE TITLE
Rating scale does not react in form_base plugin for Expyriment backend

### ISSUE THREAD

**Issue by PascalKieslich** [open-cogsci/OpenSesame#621]
In OpenSesame 3.2.4, the rating scale does not react in the form_base plugin when using the xpyriment backend. That is, if I click on a node it will not be displayed as selected. It works when switching the backend to legacy.

The example below can be used as a test case:

```
set timeout infinite
set spacing 20
set rows "1;1;1;1;1;1;1;1;1;1"
set only_render no
set margins "10;10;10;10"
set description "A generic form plug-in"
set cols "1;1;1;1;1;1;1;1;1;1;1;1"
set _theme gray
widget 4 3 7 1 rating_scale nodes="Option<br>one;Option<br>two;Option<br>three" var=rating
widget 5 9 2 1 button text=Ok
```

**Comment by smathot** [comment]
Hi Pascal,

Thanks for reporting this! For me this works fine though. What operating system are you using, and which Python version?

Cheers!
Sebastiaan

**Comment by PascalKieslich** [comment]
Hi Sebastiaan,
I am using OpenSesame 3.2.4 in the Python 2 version with Windows 7. It only is a problem when using the xpyriment backend.
Best,
Pascal

**Comment by smathot** [comment]
Hi Pascal,

I still haven't been able to reproduce this. Is this something that happens specifically on one system? If not, do you have a way to reliably reproduce it?

Cheers!
Sebastiaan

**Comment by PascalKieslich** [comment]
Hi Sebastiaan,

I looked at the issue again. It works fine on Mac OS and on a laptop running Windows 7 with a standard 1600 x 900 px display. The problem occurs on my own laptop that also runs Windows 7 but has a 3k display (2880 x 1620 px). There it does not work at all if my display scaling is 150 %. It somewhat works if I change the display scaling to 100 % (i.e., I have to try and click a few times until a box is selected). If I switch the backend from expyriment to legacy everything works fine regardless of the display scaling. Maybe it is a very specific issue with my screen so you don't have to look into it for now (we don't run actual experiments on my laptop anyway).

Best,

Pascal

**Comment by smathot** [comment]
Ah ok, that's what I thought, it's related to display scaling. That's definitely an issue that's on the radar, but not something that's specific to forms. So I'll close this issue. Thanks!
