### ISSUE TITLE
<br> tag does not work in rating_scale in form_base plugin

### ISSUE THREAD

**Issue by PascalKieslich** [open-cogsci/OpenSesame#622]
In OpenSesame 3.2.4, the `<br>` tag does not work in the rating scale in the form_base plugin. That is, a `<br>` will not result in a line break but will be displayed as `<br>`. This problem seems to be backend independent.

The example below can be used as a test case:

```
set timeout infinite
set spacing 20
set rows "1;1;1;1;1;1;1;1;1;1"
set only_render no
set margins "10;10;10;10"
set description "A generic form plug-in"
set cols "1;1;1;1;1;1;1;1;1;1;1;1"
set _theme gray
widget 4 3 7 1 rating_scale nodes="Option<br>one;Option<br>two;Option<br>three" var=rating
widget 5 9 2 1 button text=Ok
```

**Comment by smathot** [comment]
Closed in a956df2c367a7e656e6496feb8318b4cc7a4b3da
