### ISSUE TITLE
Mouse positions and responses not flushed when using psychopy as a backend

### ISSUE THREAD

**Issue by SylvainMad** [open-cogsci/OpenSesame#628]
Hello,

Eduard asked me to open an issue here.
In version 3.2.4, when running several sketchpad successively, each associated to a mouseclick, and only on the psychopy backend, only the first sketchpad waits for a mouseclick. The other one are just displayed and disappear as if the answer had already been given. In order to fix this you have to insert "fake" mouse_response in between the sketchpad. Moreover, if the cursor is visible it is not resetted at the center between sketchpad.
This issue does not appear when using the xpyriment backend.

Thanks!

**Comment by smathot** [comment]
Hi Sylvain,

Thanks for reporting this! This probably results from the `sketchpad` not flushing events.

Cheers,
Sebastiaan
