### ISSUE TITLE
roll command of loop item does not accept variables.

### ISSUE THREAD

**Issue by dschreij** [open-cogsci/OpenSesame#648]
OS 3.2.5

I tried to implement a (very simplistic) counterbalancing procedure by adding

```roll [subject_nr]```

to the relevant loop item, but `[subject_nr]` is taken literally, and not parsed as a variable. 
Is this intended, or can you reproduce this?

**Comment by smathot** [comment]
> Is this intended, or can you reproduce this?

No and yes :-)
