### ISSUE TITLE
Display isn't updated after resuming from pause

### ISSUE THREAD

**Issue by smathot** [open-cogsci/OpenSesame#649]
When you click 'Esc', the pause screen appears. When you then press 'Space' to resume, the display isn't updated until the experiment draws a new display. This can give the appearance that the experiment is frozen. In the ideal case, the display would be restored, but a cheap alternative would be to present an explicit resume message.

**Comment by wolfgangwalther** [comment]
This is indeed a cheap alternative! Just stumbled over this again. I do know how it behaves, but my experimenters do not - it's not very intuitive, if the trial "behind" the break is waiting for a specific response indefinitely and the whole "Resuming ..." screen appears to be just hanging.

To implement this, I guess the canvas implementations need a way to copy the currently displayed screen - to be able to restore that later.

This is somewhat related to #658.
