### ISSUE TITLE
Psycho back-end interprets orientation of Gabors horizontally mirrored. 

### ISSUE THREAD

**Issue by aytackarabay** [open-cogsci/OpenSesame#656]
I am working on an attentional blink-precision project where participants need to recall orientations of targets, and direct recall is asked, and responses are collected with joystick input. 

I wanted to use psycho as a back-end because it is better compared to legacy when it comes to timing. When I use legacy or experiment, the joystick input works perfectly. However, when I switch to psycho, the joystick input is horizontally mirrored. For example, let's say you move the joystick axis to the direction of 1 o'clock, psycho backend interprets it as 11 o'clock. This could be either as a result of how psycho backend processes joystick input or it can be related to how psycho backend presents visual stimuli. 

I find this issue very important, because if the problem is as a result of stimuli generation, changing a back-end cause a lot of misinterpretations of the experiments. However, if the issue is just about joystick input, it can be easily solved. 

I am not 100% sure, but I tested my experiment and data, and it seems that psycho interprets rotation of the gabors differently than legacy. It seems the issue is not related to joystick input but stimuli generation. 

I attached an example experiment, it is a work in progress experiment. Note that you need a joystick to run this experiment. First, try the experiment with legacy, and later try the experiment with psycho. You will clearly see what the issue is at response collection. 

[AB_precision_otantic_v1.0.osexp.zip](https://github.com/smathot/OpenSesame/files/2884175/AB_precision_otantic_v1.0.osexp.zip)

**Comment by smathot** [comment]
Thanks for spotting this! It indeed had to do with inconsistent treatment of the Gabor orientation. The psycho behavior of positive values being clockwise is now used for all backends.
