### ISSUE TITLE
error: failed to load audio (picture) samples

### ISSUE THREAD

**Issue by epicaliya** [open-cogsci/OpenSesame#664]
Please, help! I can´t run the experiment, although everything seems to be coordinated. This is how the error message looks like:

Stopped
The experiment did not finish normally for the following reason:
Failed to load sample: 1.wav

Details
item-stack: experiment[run].practice_loop[run].block_loop_practice_1[run].trial_sequence_practice[prepare].audio_practice[prepare]
time: Tue May 14 14:09:41 2019
exception type: osexception
exception message: ` openexp._sampler.legacy.init() the file '1.wav' does not exist

**Comment by dschreij** [comment]
Hi @epicaliya,
Please direct all your questions regarding experiments to our forum: http://forum.cogsci.nl/.
You will get appropriate help there.
