### ISSUE TITLE
OSWeb Converting of JATOS to CSV files broken on OS 3.3.0

### ISSUE THREAD

**Issue by mariansauter** [open-cogsci/OpenSesame#689]
OS: win32
OpenSesame: 3.3.0
Python: 3.7.6

`Traceback (most recent call last):`

`File "C:\Users\marsa\Downloads\opensesame_3.3.0-py37-win64-1\opensesame_3.3.0-py37-win64-1\share\opensesame_extensions\oswebext\oswebext_widget.py", line 174, in `_convert_results`
    dm = data.parse_jatos_results(jatos_results_path)
  File "C:\Users\marsa\Downloads\opensesame_3.3.0-py37-win64-1\opensesame_3.3.0-py37-win64-1\Lib\site-packages\osweb\data.py", line 40, in parse_jatos_results
    for line in fd:
  File "C:\Users\marsa\Downloads\opensesame_3.3.0-py37-win64-1\opensesame_3.3.0-py37-win64-1\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1965: character maps to <undefined>`

**Comment by mariansauter** [comment]
JATOS version: 3.5.2

**Comment by smathot** [comment]
Thanks! This issue already came in as an automatic bug report (maybe submitted by you?), and is tracked at smathot/opensesame-extension-osweb#17. (So I'm closing this issue.)
