### ISSUE TITLE
Better handling of newlines in loop and sketchpad items

### ISSUE THREAD

**Issue by smathot** [open-cogsci/OpenSesame#69]
http://forum.cogsci.nl/index.php?p=/discussion/78/open-forcing-newlines-in-loop-variables-andor-sketchpad-text-elements#Item_1

**Comment by JdenHartog** [comment]
Ignore this.
I wanted to refer to:
https://github.com/smathot/osdoc/pull/69
not:
https://github.com/smathot/OpenSesame/issues/69
Sorry!
