### ISSUE TITLE
javascript inline scripts should raise an exception when attempting to use undefined vars

### ISSUE THREAD

**Issue by MichlF** [open-cogsci/OpenSesame#692]
Posted this already in the forum but realized it is probably better to post it here.

I just used the array.splice method to insert a string into an array of strings like so:

```
var myArray = ['first', 'second', 'third'];
myArray.splice(2, 0, vars.myString);
```
vars.myString was not defined so what I ended up with is `['first', 'second', None, 'third']` instead of a four string array.

Would it not make more sense if OS raises an exception if a variable is not defined?

Cheers,

M

**Comment by smathot** [comment]
Thanks for thinking along. This would make sense to me, and I don't see any obvious downsides. @dschreij What do you think?

PS. For future reference, the code for OSWeb lives at https://github.com/smathot/osweb.

**Comment by dschreij** [comment]
That would make sense indeed. I think we need a proxy on the VarStore object for that, but that should be minimal effort to implement. We only need to watch for 'gets' for properties and issue a warning if it doesn't exist. 
Shall I recreate this issue on smathot/osweb (as it is not possible to move it?). It's better to discuss the specifics there.

**Comment by dschreij** [comment]
Closed in favor of https://github.com/smathot/osweb/issues/14
