### ISSUE TITLE
Numpad keys as allowed responses raise exceptions

### ISSUE THREAD

**Issue by MichlF** [open-cogsci/OpenSesame#693]
Posted this already in the forum but realized it is probably better to post it here.

Not sure whether this is already a known issue but when setting numpad / keypad keys (e.g. KP_1 or NUM_1) as allowed responses in a response item will raise an exception and break the experiment in the browser but not in OpenSesame. Compatibility check does not recognize this error.

Exception:

> Application Errror
> 
> Uncaught TypeError: Cannot read property '0' of undefined
> 
> 
> See the console for further details

**Comment by smathot** [comment]
Thanks for reporting this. We already have a PR for this issue (smathot/osweb#10), so I'm closing it here :-)
