### ISSUE TITLE
name 'unicode' is not defined from media_player_mpy Plugin

### ISSUE THREAD

**Issue by mariansauter** [open-cogsci/OpenSesame#699]
Currently, the media player plugin does not work at all. 

ERROR:
    item-stack: experiment[run].training_loop[run].training_blocks[run].trainig_trials[run].training_sequence[prepare].gif_stimuli[prepare]
    time: Fri May 29 12:52:23 2020
    exception type: NameError
    exception message: name 'unicode' is not defined

The error seems to be a remainder from the Python 2 to 3 transition.

MY HOTFIX:
Navigate to
`OpenSesame\share\opensesame_plugins\media_player_mpy`
and open `media_player_mpy.py`

in line 139, change
`[unicode,str]`
to
`[str]`

**Comment by dschreij** [comment]
Hi @mariansauter, thanks for taking the time to report this.
This has just been fixed in `v0.1.9`
