### ISSUE TITLE
Inserting a line break in long code line freezes Open Sesame

### ISSUE THREAD

**Issue by MichlF** [open-cogsci/OpenSesame#701]
I stumbled across a weird issue when I try to insert a line break in a long code line in the editor. I have attached the experiment file for reproduction. When pressing enter when the cursor is position somewhere in the middle of the code line, Open Sesame freezes and throws the following error in the CMD:

`SubprocessManager:60:WARNING] main process is alive but unresponsive`

How to reproduce:
1. Open file: [Zhao_rep1.zip](https://github.com/smathot/OpenSesame/files/4908370/Zhao_rep1.zip)
2. Open run phase of inline script `blockFeed` in editor
3. Click, for example, on the position after `var.count_blockAcc`
4. Press enter.

When following the same procedure after activating the option "View script" on the top right everything works flawlessly. However, even when returning to the "View controls" screen and deleting the line break and redoing the procedure, it will crash again. This leads me to believe it might have something to do with the linting of the editor?

I am using Open Sesame 3.3.3, Win10 and the Opensesame installation via Anaconda distribution.

**Comment by smathot** [comment]
Thanks for this! It's a bug in https://github.com/smathot/pyqode.python. The warning that you get indicates that the program is stuck in a loop (possibly infinite, but at least very long).

**Comment by smathot** [comment]
Fixed in smathot/pyqode.python#1. You should be able to fix it by updating pyqode.core and pyqode.python:

```
conda update pyqode.core pyqode.python -c cogsci -y
```
