### ISSUE TITLE
Using var. transforms a number string into an integer

### ISSUE THREAD

**Issue by MichlF** [open-cogsci/OpenSesame#703]
Using var. leads to a very confusing error:

```
# A list of strings each containing a number
list_str_ints = ["1", "20", "300", "4000", "50000"]

# Stays a string
a_str = list_str_ints.pop()

# Becomes an int
a_int = list_str_ints.pop()
var.a_int = a_int

# Becomes an int
var.a_int2 = list_str_ints.pop()

# Remains a string
var.a_str2 = list_str_ints[:2]

# Becomes an int
var.a_int3 = list_str_ints[0]
```
```
print(a_str, type(a_str), var.a_int, type(var.a_int), var.a_int2, type(var.a_int2), var.a_str2[0], type(var.a_str2[0]), var.a_int3, type(var.a_int3))
```

> 50000 <class 'str'>
> 4000 <class 'int'>
> 300 <class 'int'>
> 1 <class 'str'>
> 1 <class 'int'>

In other words, it does not depend on using an built-in method like pop(). The print output happens when running the experiment and is directly from the console.

I am using Open Sesame 3.3.3, Win10 and the Opensesame installation via Anaconda distribution.

EDIT:
Not an issue when using a for loop:
```
a_list = ["1", "2", "3"]
var.another_list = ["1", "2", "3"]

for elem in a_list:
    var.elem=elem
    print(elem, type(elem), var.elem, type(elem))
    
for elem in var.another_list:
    var.elem=elem
    print(elem, type(elem), var.elem, type(elem))
```

> 1 <class 'str'> 1 <class 'str'>
> 2 <class 'str'> 2 <class 'str'>
> 3 <class 'str'> 3 <class 'str'>
> 1 <class 'str'> 1 <class 'str'>
> 2 <class 'str'> 2 <class 'str'>
> 3 <class 'str'> 3 <class 'str'>

**Comment by eort** [comment]
Hi Michel, 

That behaviour is intentional if you use the var object. Across all your examples, the consistency is whether or not you store a variable as part of `var`. If you are, strings containing (only) numbers are converted to numbers. See [this part of the manual](https://osdoc.cogsci.nl/3.3/manual/variables/#smart-variable-typing-and-some-pitfalls)

**Comment by MichlF** [comment]
Hi Eduard,

ah, thanks. I see, didn't know it was intended.

On a personal note though, do the benefits of this really outweigh the advantages? It is neither normal Python nor is it really pythonic. At worst, it can lead to seriously hard to debug issues. At best, it spares you from specifically declaring the type of a variable (i.e. with `str()`, `float()`, etc.) which doesn't strike me as such a huge advantage.
It is also not helpful that it behaves totally different when used as an iterator within a for loop.

I closed this issue but it would be interesting to hear @smathot  or @dschreij opinion on this.

**Comment by dschreij** [comment]
I like the automatic casting, as for some people the difference between "1" and 1 is still very difficult, so when they then for instance do arithmetic with vars in var while the variable contains a string this has unexpected results (eg concatenation as "1" + "1" becomes "11"). I understand for the more advanced user this automatic casting may be cumbersome, but I have never had any problems with it myself once I know that it happens.

I do agree that the behavior should be consequent across different situations though, so also in loops.

**Comment by smathot** [comment]
The main reason for doing this was to allow people to write conditional statements without having to worry about types. E.g. `[cue] = left` or `[cue] = "left"` or `[correct] = 1`. The way it has been implemented isn't ideal, and it can indeed be unpredictable. But it's difficult to change while maintain backwards compatibility so I don't have any plans to change that in the near future.
