### ISSUE TITLE
Opensesame.bat does does not work when launched from other drives

### ISSUE THREAD

**Issue by Martin2Constant** [open-cogsci/OpenSesame#704]
Hello,

When trying to launch opensesame.bat from another drive than the one OpenSesame is installed on, the script fails to launch OpenSesame.

The fix is simple: add the "/D" argument in line 2, "cd %~dp0" --> "cd /D %~dp0". 
It shouldn't break anything and allows for launching experiment files directly from a USB drive for instance.

Best regards,
Martin Constant.

**Comment by smathot** [comment]
Thank you! I'll rebuild the packages for 3.3.3, because this seems like quite a nasty issue for some people.

**Comment by smathot** [comment]
Was closed in the packaging of 3.3.4.
