### ISSUE TITLE
Feature request: Login to OSF with ORCID account

### ISSUE THREAD

**Issue by MichlF** [open-cogsci/OpenSesame#706]
Hi Sebastiaan,

not sure whether this is under your control but it would be great if one could log in to OSF with the ORCID account directly. This is actually possible when I navigate to the regular login page on the OSF homepage, using the in-window browser. However, it would be great if that is an option directly instead of having to click through the menu.

Cheers,
Michel

**Comment by smathot** [comment]
Thanks for pointing this out. I've moved the issue here: dschreij/QOpenScienceFramework#21
