### ISSUE TITLE
Error messages block buttons

### ISSUE THREAD

**Issue by MichlF** [open-cogsci/OpenSesame#712]
Something that's been bugging me for awhile:
The error message window is blocking some crucial buttons and GUI options (as can be seen in [here](https://github.com/smathot/OpenSesame/files/4974334/blocked.zip) for the fullscreen, controls and help button in the sketchpad item).

Would it be possible to let it appear somewhere else?

**Comment by smathot** [comment]
Thanks for pointing this out. I opened the issue in the dschreij/QNotifications which is where this is implemented.
