### ISSUE TITLE
Feature request: allow specific key response for sketchpad/feedback items

### ISSUE THREAD

**Issue by MichlF** [open-cogsci/OpenSesame#713]
Currently, there is only the option to define `duration` in ms or _any_ `keypress` for sketchpad/feedback items. On many occasions I wished there was an option to define the key that has to be pressed in order to advance to the next item in the sequence. In other words, would it be possible to allow for defining a specific key that has to be pressed in order to advance from the current sketchpad/feedback item to the next item? At least in the GUI, this could be done by accepting any string in sketchpad/feedback items that is also allowed/interpreted as key in response items. `keypress` could remain the same and any integer is interpreted as duration in ms.

I understand that I could set the duration to 0 and slap a response item directly after the sketchpad/feedback item but this can lead, depending on the sequence design, to quite a lot of "unnecessary" items. Especially with online experiments where mostly items and no inline coding is used, as well as while the bug with too many linked items causing freezes is still around, this would be a great option.

**Comment by smathot** [comment]
> At least in the GUI, this could be done by accepting any string in sketchpad/feedback items that is also allowed/interpreted as key in response items.

What do you mean exactly with this?

You can already implemented this by editing the script of a `sketchpad` and adding a line such as:

```
set allowed_responses space
```

That's sufficient, right? It avoids cluttering the interface, and for those people who really need this functionality it's there. But this does seem to crash on OSWeb.

**Comment by MichlF** [comment]
Ah ok, my bad. I wasn't aware that this is possible. Can be closed if that bug you've mentioned is tracked somewhere else.
