### ISSUE TITLE
Timeout field in keyboard_response is not compatible with placeholder in OSWeb mode.

### ISSUE THREAD

**Issue by wangmoods** [open-cogsci/OpenSesame#714]
I used placeholder in the *Timeout* field of keyboard_response item. The variable represented by the placeholder was defined in previous codes. When it was run in Python mode, it works perfectly. But when it was run in OSWeb mode, it worked as if the *Timeout* field was filled with ```infinite```.
In another word, I cannot limit the time window of response with a placeholder of *Timeout* field in keyboard_response under OSWeb mode.

OS: windows 10
Browser: Firefox 79.0 (64-bit)

I've already reported the bug at the [support forum](
https://forum.cogsci.nl/discussion/6346/timeout-in-keyboard-response-does-not-support-placeholder-in-osweb).

Here's a short demo for this bug.
[bug_demo.zip](https://github.com/smathot/OpenSesame/files/5001660/bug_demo.zip).

Thank you.

**Comment by dschreij** [comment]
Hi @wangmoods, thanks for reporting this.
Please file this bug at https://github.com/smathot/osweb/issues, which is where the issue tracker of osweb lives.

**Comment by wangmoods** [comment]
> Hi @wangmoods, thanks for reporting this.
> Please file this bug at https://github.com/smathot/osweb/issues, which is where the issue tracker of osweb lives.

Done. https://github.com/smathot/osweb/issues/29 .
