### ISSUE TITLE
Checkbox being checked is not registered if text is empty

### ISSUE THREAD

**Issue by PierreYvesH** [open-cogsci/OpenSesame#717]
Hi, so if I create a form and add a checkbox
`
chkbx = widgets.checkbox(
                    form, 
                    "", 
                    center=True, 
                    var=var)
`
Then when I check it while running, its value never changes because the variable `l_val ` is empty. An easy fix would be to append `widget.checked` instead of `widget.text` line 218.

**Comment by smathot** [comment]
Thanks for flagging this, that's really useful!
