### ISSUE TITLE
"Help" in menubar not loading, stuck on " Please Wait"

### ISSUE THREAD

**Issue by kolfers** [open-cogsci/OpenSesame#724]
When I click on the 'Help' in the menubar, I only see " Please wait..."

I'm using OpenSesame 3.3.3 installed via the Megapack Windows Installer on a Windows 10 machine with all updates installed.

I've had the same problem on a second Windows 10 machine were I installed using the standard 3.3.3 installer. 

Eduard has   [reported](https://forum.cogsci.nl/discussion/6468/help-in-menubar-not-loading-stuck-on-please-wait) similar problems on Ubuntu 18.04 (conda installation)

![image](https://user-images.githubusercontent.com/545578/94803482-a4ad0d80-03e9-11eb-9218-a58e62c9a45c.png)

**Comment by smathot** [comment]
Thanks for this!
