### ISSUE TITLE
[ISSUE] KeyPress 

### ISSUE THREAD

**Issue by DiogoAABranco** [open-cogsci/OpenSesame#761]
Hi guys.

I'm making a GoNoGo task participants should press the SPACEBAR when a circle appears and withhold response when a square appears.
I'm running the task on OSWEB in a JATOS server.  
In the task, the keypress is on the spacebar and my issue is that if the participant continues pressing the spacebar without lifting the finger the task continues to run. This effect is undesirable since I don't want participants to speedrun the experiment. Is there any way to solve this? 

Here is a [video](https://drive.google.com/file/d/15n-m7e-ePQI-KWM3M-tB0aYavdb4Av6B/view?usp=sharing) showing the problem. 

Thank you.

**Comment by smathot** [comment]
Thanks for pointing this out. I filed an issue for this on open-cogsci/osweb#64, which is where OSWeb lives, and I will close the issue here. If you have questions about how to work around this bug for now, don't hesitate to post them on the forum!
