### ISSUE TITLE
Help icon results in 404

### ISSUE THREAD

**Issue by richlv** [open-cogsci/OpenSesame#773]
In the media player widget, browsed for a video and clicked on the question mark icon.
The opened page resulted in a 404 error: https://osdoc.cogsci.nl/3.3.10/manual/interface .

Looks like the intended URL is https://osdoc.cogsci.nl/3.3/manual/interface .

The URL seems to be built here: https://github.com/open-cogsci/OpenSesame/blob/1cb265c4beb757e93aca865d3619b68b55a9db81/libqtopensesame/widgets/tab_widget.py#L403

`main_version` is defined here: https://github.com/open-cogsci/OpenSesame/blob/9daefc269c0b0aab9c4b6795ea19e2f5063184c2/libopensesame/metadata.py#L27

Perhaps `major_version` should be used?
https://github.com/open-cogsci/OpenSesame/blob/9daefc269c0b0aab9c4b6795ea19e2f5063184c2/libopensesame/metadata.py#L29

**Comment by smathot** [comment]
Hi @richlv ,
Thanks for pointing this out. It's actually a redirection issue on the server, because these links should work. I'll look into it.
— Sebastiaan

**Comment by smathot** [comment]
Should be fixed now!
