### ISSUE TITLE
Changing experiment title (and maybe item names) in the tab is ignored when pressing 'ENTER' (Mac OS)

### ISSUE THREAD

**Issue by smathot** [open-cogsci/OpenSesame#79]
See http://forum.cogsci.nl/index.php?p=/discussion/105/open-minor-v0-25-mac-os-x-hitting-enter-does-not-change-experiment-name#Item_1

**Comment by smathot** [comment]
@dschreij What's the status on this?

**Comment by dschreij** [comment]
This works correctly now (OS 3.1.2 Qt4 and Qt5)
