### ISSUE TITLE
libtobii unreliable in pygaze

### ISSUE THREAD

**Issue by dev-jam** [open-cogsci/OpenSesame#793]
I found Tobii is still available in the pygaze plugin. libtobii has unuseable timestamps and suffers from missing samples.
Can you please disable tobii/libtobii in pygaze until this is resolved and point the users to the following issue:

https://github.com/esdalmaijer/PyGaze/issues/173

**Comment by smathot** [comment]
Thanks for pointing this out. It's indeed a problem, but since it's not related to OpenSesame I'm closing the issue here!
