### ISSUE TITLE
Gazepoint eye tracker - multiple fixations with the same FPGOID

### ISSUE THREAD

**Issue by kjaksic** [open-cogsci/OpenSesame#814]
Enviornment: 

-win 11 
-OpenSesame 4.0.24  
-Gazepoint GP3 60 Hz

Design: 
-two pictures are simultaneously presented on the left and right side of the screen for 10 seconds

Current behavior: 
- tsv file contains multiple fixations with the same ID (e.g. FPGOID = "181" for n fixations, then "182" for n fixations) 

Expected behavior: 
-each fixation would have its unique ID as is the case when collecting data with Gazepoint analysis  (e.g. FPGOID = 1......n)  

Question: 
How the same ID for multiple fixations can be explained and is it correct to treat consecutive fixations as independent events, regardless of the ID? Time variable suggest that fixations are correctly updated every 16.6 ms.  

Thank you.

**Comment by smathot** [comment]
Thanks for bringing this issue up. Could you repost this in the PyGaze repository though? (And then close the issue here.) This functionality is not part of OpenSesame itself.

- https://github.com/esdalmaijer/PyGaze/issues
