### ISSUE TITLE
latest release executable win64-1.exe is missing

### ISSUE THREAD

**Issue by flagoda** [open-cogsci/OpenSesame#818]
Hi, 
On the latest release executable win64-1.exe is missing.
We use this github api (
https://api.github.com/repos/open-cogsci/OpenSesame/releases/latest) to automate or softwares upgrade but can't work with OpenSesame because the latest executable version is not on the latest page.
Is it possible to have this ?

**Comment by smathot** [comment]
I don't create new packages for each release, because updating can now be handled but through the automatic updater. But I know tagged the last release that is packages as the latest release, so that should work for your purposes.
